-- V3__curated_public_hospitals.sql
-- Hospitality: Curated Public Dataset Hospitals Migration
-- ==========================================================================
-- DATA PROVENANCE AUDIT:
-- Source Dataset: hospital_directory.csv (Open Government Data - National Hospital Directory)
-- Total Source Rows Inspected: 30273
-- Verified Records Selected: 35 (Assigned IDs 11 to 45)
-- Existing Pre-Seeded IDs Preserved: 1 to 10 (Total Final Hospitals: 45)
-- Cities Represented: Bengaluru Urban, Hyderabad, Mumbai, Chennai
-- 
-- PUBLIC DATASET FIELDS SOURCED DIRECTLY:
-- - Hospital Name (hospital_directory.csv -> Hospital_Name)
-- - Location / City / State (hospital_directory.csv -> District / State / Location)
-- - Full Address & Pincode (hospital_directory.csv -> Address_Original_First_Line + Pincode)
-- - Specialties (hospital_directory.csv -> Specialties)
-- 
-- SIMULATED / INDICATIVE DEMO DATA ENRICHMENT:
-- Notice: The following fields are simulated indicative demo data added specifically
-- for hospital-policy decision support prototyping and are NOT sourced from the public CSV:
-- - Room Categories & Tiers (General Ward, Semi-Private, Single Deluxe, ICU)
-- - Indicative Daily Room Costs (INR 1,200 to INR 14,000 / day)
-- - Room Availability Flags
-- - Insurer Network Mappings (Tie-ups for Star Health, HDFC ERGO, Care Health)
-- These simulated attributes do not constitute commercial hospital tariffs or real contracts.
-- ==========================================================================

-- 1. Insert 35 Curated Public Dataset Hospitals (IDs 11 to 45)
INSERT INTO hospitals (id, name, location, address, network_status, description) VALUES
(11, 'St.John''s Medical College Hospital', 'Bengaluru Urban, Karnataka', 'Sarjapur Road, John Nagar, Koramangala - 560034', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Anaesthesiology, Clinical Nutrition, Clinical Psychology, Dental Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #12625]'),
(12, 'Abhaya Eye Hospital, Super Speciality Eye Care Centre', 'Bengaluru Urban, Karnataka', '# 77, 100 Ft.Ring Road, B.S.K.3rd Stage, 5th Block - 560085', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Cataract. [Public Dataset Source: hospital_directory.csv, Sr. #12639]'),
(13, 'Abhaya Hospital', 'Bengaluru Urban, Karnataka', '17, Dr.M.H.Mari Gowda Road, Opp Wilson Garden - 560027', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Neuro Psychiatry, Neuro Surgery, Oncology, Orthopaedics. [Public Dataset Source: hospital_directory.csv, Sr. #12640]'),
(14, 'Abhishek Netradhama', 'Bengaluru Urban, Karnataka', 'HIG 2024, 3rd B Cross, B Sector, Opposite national public school, Near SBI Bank Yelahanka new town - 560160', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Cataract Services, Glaucoma Services, Cornea Services, Refractive Surgery services. [Public Dataset Source: hospital_directory.csv, Sr. #12641]'),
(15, 'Aditya Netralaya', 'Bengaluru Urban, Karnataka', 'No.244, 7th cross, VI Block, III Phase,\nBanashankari III Stage, Opposite Kamakya Theatre - 560085', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Outpatient Department, Cataract surgery, Glaucoma care, Diabetic retinopathy. [Public Dataset Source: hospital_directory.csv, Sr. #12643]'),
(16, 'Apollo Bengaluru Cradle Limited', 'Bengaluru Urban, Karnataka', 'No.58.5th Cross, 18th Main Dhanlakshmi Bank Building - 560095', 'OUT_OF_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Maternity Services, Birthing, Fertility  and IVF, Woman''s Health. [Public Dataset Source: hospital_directory.csv, Sr. #12646]'),
(17, 'Apollo Speciality Hospital', 'Bengaluru Urban, Karnataka', '21/2, 14th Cross, 3rd Block, Jayanagar - 560011', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Cardiac surgery, General and  Gastro-intestinal surgery, Gynecology, Pediatric surgery. [Public Dataset Source: hospital_directory.csv, Sr. #12648]'),
(18, 'Athreya Hospital', 'Bengaluru Urban, Karnataka', '6/2 B, Opposite Suryanagara, Phase 1, Chandpura, Anekal Main Road - 560081', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Obstetrics and  Gynaecology, Radiology, Paediatrics and  Neonatology, Cardiology. [Public Dataset Source: hospital_directory.csv, Sr. #12649]'),
(19, 'Bharathy Hospital', 'Bengaluru Urban, Karnataka', '4, Nagarbhavi Main Road, Prasanthnagar - 560079', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Emergency and  Accident Trauma Care (with Free Ambulance), ICU (For Accident victims with highest quality anesthetic facilities), CT Scan Centre, Blood Bank. [Public Dataset Source: hospital_directory.csv, Sr. #12657]'),
(20, 'Chanre Rheumatology And Immunology Centre And Research', 'Bengaluru Urban, Karnataka', '#149, 15th Main Road Nhcl - 560079', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Rheumatology and immunology, Immunodeficiency, Advanced arthritis Clinic, Allergy. [Public Dataset Source: hospital_directory.csv, Sr. #12658]'),
(21, 'Chinmaya Mission Hospital', 'Bengaluru Urban, Karnataka', '1st stage, Indiranagar - 560038', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include General Medicine, OB and  G Laparoscopic Surgery, General Surgery Urology Paediatric Surgery, Orthopedics with superspecialities Neurology Surgical Gastro-Enterology. [Public Dataset Source: hospital_directory.csv, Sr. #12659]'),
(22, 'Chinmaya Narayana Super Specialty Centre', 'Bengaluru Urban, Karnataka', 'C.M.H.Road, Indiranagar, 2nd Stage - 560038', 'OUT_OF_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Anaesthesia and  Critical Care, Blood Bank, Cardiac Surgery  Adult, Cardiac Surgery  Paediatric. [Public Dataset Source: hospital_directory.csv, Sr. #12660]'),
(23, 'Chord Road Hospital Pvt Ltd', 'Bengaluru Urban, Karnataka', '#100/101, Lic Colony West Of Chord, Basaveshwaranagar - 560079', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Physicians, General Surgeons, Anaesthesiologists, Ear. [Public Dataset Source: hospital_directory.csv, Sr. #12661]'),
(24, 'Cloud Nine, Jayanagar', 'Bengaluru Urban, Karnataka', '#1533, 9th Main,\n3rd Block, Jayanagar - 560011', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Maternity, Gynaecology, Pediatrics, Intensive Care. [Public Dataset Source: hospital_directory.csv, Sr. #12662]'),
(25, 'Deepa Hospital', 'Bengaluru Urban, Karnataka', '#27, Old Madras Road - 560036', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include Gyanecology, Medicine, Maternity, Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #12666]'),
(26, 'Devi Eye Hospital', 'Bengaluru Urban, Karnataka', '#434, 18th Main, 80 Feet Road, 6th Block, Opposite Koramangala Bus Depot, Koramangala - 560095', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include i design laser vision correction, Lasik and  Intralase (Laser Vision Correction for Short Sight - Long Sight Astigmatism), Phaco Emulsification with Foldable Lens (Cataract with IOL), Topography. [Public Dataset Source: hospital_directory.csv, Sr. #12667]'),
(27, 'Divakars Speciality Hospital', 'Bengaluru Urban, Karnataka', '220, 2nd phase, JP Nagar,\nNext to Nilgiris - 560078', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Bengaluru Urban, Karnataka. Clinical specialties include General Gynecology, Obstetrics, Prenatal Care, nulife clinic. [Public Dataset Source: hospital_directory.csv, Sr. #12668]'),
(28, 'Care Hospital, Banjara', 'Hyderabad, Andhra Pradesh', 'Road No.1, Banjara Hills - 500034', 'OUT_OF_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Anaesthesiology, Bio-Chemistry, Cardiac Yoga, Cardiology. [Public Dataset Source: hospital_directory.csv, Sr. #6]'),
(29, 'L V Prasad Eye Institute', 'Hyderabad, Andhra Pradesh', 'Kallam Anji Reddy Campus, L V Prasad Marg, Banjara Hills - 500034', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Ophthalmology. [Public Dataset Source: hospital_directory.csv, Sr. #563]'),
(30, 'Apollo Hospitals', 'Hyderabad, Andhra Pradesh', 'Jubilee Hills - 500033', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Cardiology, Cardiothoracic Surgery, Cosmetic Surgery, Cosmetology. [Public Dataset Source: hospital_directory.csv, Sr. #564]'),
(31, 'Mediciti Hospital', 'Hyderabad, Andhra Pradesh', '5 - 9 - 22, Secretariat Road - 500063', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Anaesthesiology, Cardiology, Cardiothoracic Surgery, Critical Care. [Public Dataset Source: hospital_directory.csv, Sr. #565]'),
(32, 'KIMS Hospital, Secunderabad', 'Hyderabad, Andhra Pradesh', 'Secunderabad, 1 - 8 - 31/1, Minister Road, Secunderabad - 500003', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Accident and Emergency, Anaesthesiology, Bariatric Surgery, Bone Marrow. [Public Dataset Source: hospital_directory.csv, Sr. #566]'),
(33, 'Kamineni Hospital', 'Hyderabad, Andhra Pradesh', 'L.B Nagar - 500074', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Anaesthesiology, Bariatric Surgery, Cardiology, Cardiothoracic Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #567]'),
(34, 'Yashoda Hospital', 'Hyderabad, Andhra Pradesh', 'Somajiguda, Rajbhavan Road - 500082', 'OUT_OF_NETWORK', 'Multi-specialty healthcare facility located at Hyderabad, Andhra Pradesh. Clinical specialties include Anaesthesiology, Cardiac Anesthesia, Cardiology, Cardiothoracic Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #568]'),
(35, 'Breach Candy Hospital, Mumbai', 'Mumbai, Maharashtra', '60-A, Bhulabhai Desai Road, Breach Candy - 400026', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Bariatric Surgery, Cardiology, Cardiothoracic Surgery, Cosmetic Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #17637]'),
(36, 'Cumbala Hill Hospital and Heart Institute', 'Mumbai, Maharashtra', '93/95, August Kranti Marg, August Kranti Maidan - 400036', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Cardiologist, Ophthalmology, Neurology, Oncology. [Public Dataset Source: hospital_directory.csv, Sr. #17638]'),
(37, 'Asian Heart Institute And Research Center', 'Mumbai, Maharashtra', 'G/N Block, Opposite ICICI Tower, Bandra Kurla Complex, Bandra(E) - 400051', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Cardiology, Cardiothoracic Surgery, Critical Care, Diabetology. [Public Dataset Source: hospital_directory.csv, Sr. #17639]'),
(38, 'Lilavati Hospital and Research Center', 'Mumbai, Maharashtra', 'A-791, Bandra Reclamation, Bandra(W), Mumbai - 400050', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Anesthesiology, Audiology and Speech Therapy, Cardiology, Cardiothoracic Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #17640]'),
(39, 'Tata Memorial Hospital', 'Mumbai, Maharashtra', 'Dr.E Borges Road, Parel - 400012', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Anesthesiology, Bio-Chemistry, Dentistry, General Medicine. [Public Dataset Source: hospital_directory.csv, Sr. #17641]'),
(40, 'Bhatia General Hospital', 'Mumbai, Maharashtra', 'Chikalwadi, J Dadaji Road, Tardeo - 400007', 'OUT_OF_NETWORK', 'Multi-specialty healthcare facility located at Mumbai, Maharashtra. Clinical specialties include Andrology, Audiology and Speech Therapy, Cardiology, Cardiovascular Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #17642]'),
(41, 'Dr.Kamakshi Memorial Hospital', 'Chennai, Tamil Nadu', '6/13, 3rd Cross Street, Kasthuribai Nagar, Adyar - 600020', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Chennai, Tamil Nadu. Clinical specialties include Anaesthesiology, Cardiology, Cardiothoracic Surgery, Cosmetology. [Public Dataset Source: hospital_directory.csv, Sr. #24174]'),
(42, 'Vijaya Hospital', 'Chennai, Tamil Nadu', 'No.434, N.S.K.Salai, Vadapalani - 600026', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Chennai, Tamil Nadu. Clinical specialties include Ayurveda, Cardiology, Cardiothoracic Surgery, Cardiovascular Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #24175]'),
(43, 'Fortis Malar Hospital', 'Chennai, Tamil Nadu', 'Gandhi Nagar, 52, First Main Road, Gandhi nagar, Adyar - 600020', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Chennai, Tamil Nadu. Clinical specialties include Andrology, Anaesthesiology, Cardiology, Critical Care. [Public Dataset Source: hospital_directory.csv, Sr. #24176]'),
(44, 'MIOT Hospitals', 'Chennai, Tamil Nadu', 'Manapakkam, 4/112, Mount Poonamalle Road - 600089', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Chennai, Tamil Nadu. Clinical specialties include Anaesthesiology, Cardiology, Cardiothoracic Surgery, Cardiovascular Surgery. [Public Dataset Source: hospital_directory.csv, Sr. #24177]'),
(45, 'Apollo Childrens Hospital', 'Chennai, Tamil Nadu', 'No.15, Thousand Lights, Shafee Mohammed Road - 600006', 'IN_NETWORK', 'Multi-specialty healthcare facility located at Chennai, Tamil Nadu. Clinical specialties include Adolescent medicine, Anaesthesiology, Cardiology/ Cardiothoracic surgery, Community/Behavioral medicine. [Public Dataset Source: hospital_directory.csv, Sr. #24178]');

-- 2. Insert Public Dataset Verified Specialties
INSERT INTO hospital_specialties (hospital_id, specialty) VALUES
(11, 'Anaesthesiology'),
(11, 'Clinical Nutrition'),
(11, 'Clinical Psychology'),
(11, 'Dental Surgery'),
(11, 'Dermatology'),
(11, 'Emergency Medicine'),
(11, 'General Medicine'),
(11, 'General Surgery'),
(12, 'Cataract'),
(13, 'Neuro Psychiatry'),
(13, 'Neuro Surgery'),
(13, 'Oncology'),
(13, 'Orthopaedics'),
(13, 'Joint Replacements'),
(13, 'General Surgery'),
(14, 'Cataract Services'),
(14, 'Glaucoma Services'),
(14, 'Cornea Services'),
(14, 'Refractive Surgery services'),
(14, 'Diabetic Eye Care Services'),
(14, 'Oculoplasty Services'),
(14, 'Peadiatric Services'),
(14, 'Uveitis Services'),
(15, 'Outpatient Department'),
(15, 'Cataract surgery'),
(15, 'Glaucoma care'),
(15, 'Diabetic retinopathy'),
(15, 'Age related macular degeneration'),
(15, 'Paediatric ophthalmology'),
(15, 'Refractive surgery services'),
(15, 'Contact lenses'),
(16, 'Maternity Services'),
(16, 'Birthing'),
(16, 'Fertility  and IVF'),
(16, 'Woman''s Health'),
(16, 'Women Health Checks'),
(16, 'Procedures'),
(16, 'Cancer Evaluation'),
(16, 'Children''s Health'),
(17, 'Cardiac surgery'),
(17, 'General and  Gastro-intestinal surgery'),
(17, 'Gynecology'),
(17, 'Pediatric surgery'),
(17, 'Thoracic surgery'),
(17, 'Urology'),
(17, 'Colorectal surgery'),
(17, 'Cancer surgery'),
(18, 'Obstetrics and  Gynaecology'),
(18, 'Radiology'),
(18, 'Paediatrics and  Neonatology'),
(18, 'Cardiology'),
(18, 'General Surgery and Laparoscopy'),
(18, 'ENT'),
(18, 'Orthopaedics'),
(18, 'Ophthalmology'),
(19, 'Emergency and  Accident Trauma Care (with Free Ambulance)'),
(19, 'ICU (For Accident victims with highest quality anesthetic facilities)'),
(19, 'CT Scan Centre'),
(19, 'Blood Bank'),
(19, 'Ambulance Services'),
(19, 'X-ray Centre'),
(19, 'Laboratory'),
(19, 'Pharmacy'),
(20, 'Rheumatology and immunology'),
(20, 'Immunodeficiency'),
(20, 'Advanced arthritis Clinic'),
(20, 'Allergy'),
(20, 'Physiotherapy and  Rehabilitation'),
(21, 'General Medicine'),
(21, 'OB and  G Laparoscopic Surgery'),
(21, 'General Surgery Urology Paediatric Surgery'),
(21, 'Orthopedics with superspecialities Neurology Surgical Gastro-Enterology'),
(21, 'Paediatrics Psychiatry Plastic Surgery'),
(21, 'Cardiology Neurosurgery Oral-Maxillofacial Surgery'),
(21, 'Ophthalmology Vascular Surgery Pulmonolgy'),
(21, 'E.N.T.Pathology Endocrinology'),
(22, 'Anaesthesia and  Critical Care'),
(22, 'Blood Bank'),
(22, 'Cardiac Surgery  Adult'),
(22, 'Cardiac Surgery  Paediatric'),
(22, 'Cardiology  Adult'),
(22, 'Cardiology  Paediatric'),
(22, 'Clinical Nutrition and  Dietetics'),
(22, 'Cranio-Maxillo Facial Surgery'),
(23, 'Physicians'),
(23, 'General Surgeons'),
(23, 'Anaesthesiologists'),
(23, 'Ear'),
(23, 'Nose And Throat'),
(23, 'Maxillary Surgeon'),
(23, 'Obstetricians and  Gynaecologists'),
(23, 'Orthopaedicians'),
(24, 'Maternity'),
(24, 'Gynaecology'),
(24, 'Pediatrics'),
(24, 'Intensive Care'),
(24, 'Fertility'),
(24, 'Cryonine'),
(25, 'Gyanecology'),
(25, 'Medicine'),
(25, 'Maternity'),
(25, 'Surgery'),
(25, 'Immunisation Facility'),
(25, 'Laprascopic Surgery'),
(25, 'Endoscopy'),
(25, 'Dermatology'),
(26, 'i design laser vision correction'),
(26, 'Lasik and  Intralase (Laser Vision Correction for Short Sight - Long Sight Astigmatism)'),
(26, 'Phaco Emulsification with Foldable Lens (Cataract with IOL)'),
(26, 'Topography'),
(26, 'Retinal Detachment Surgery'),
(26, 'Laser Treatment for Diabetic Disorders'),
(26, 'Retinal Fluorescein Angiography'),
(26, 'OCT'),
(27, 'General Gynecology'),
(27, 'Obstetrics'),
(27, 'Prenatal Care'),
(27, 'nulife clinic'),
(27, 'Laboratory Testing and  In-Office Surgery'),
(27, 'Medical Spa for Women'),
(27, 'Ophthalmology'),
(28, 'Anaesthesiology'),
(28, 'Bio-Chemistry'),
(28, 'Cardiac Yoga'),
(28, 'Cardiology'),
(28, 'Cardiothoracic Surgery'),
(28, 'Chest Physician'),
(28, 'Critical Care'),
(28, 'Dentistry and Maxillofacial Surgery'),
(29, 'Ophthalmology'),
(30, 'Cardiology'),
(30, 'Cardiothoracic Surgery'),
(30, 'Cosmetic Surgery'),
(30, 'Cosmetology'),
(30, 'Critical Care'),
(30, 'Diabetology'),
(30, 'Endocrinology'),
(30, 'Gastroenterology'),
(31, 'Anaesthesiology'),
(31, 'Cardiology'),
(31, 'Cardiothoracic Surgery'),
(31, 'Critical Care'),
(31, 'Dermatology'),
(31, 'Dietetics'),
(31, 'Emergency Medicine'),
(31, 'Endocrinology'),
(32, 'Accident and Emergency'),
(32, 'Anaesthesiology'),
(32, 'Bariatric Surgery'),
(32, 'Bone Marrow'),
(32, 'Transplant'),
(32, 'Cardiology'),
(32, 'Cardiothoracic Surgery'),
(32, 'Cardiovascular Surgery'),
(33, 'Anaesthesiology'),
(33, 'Bariatric Surgery'),
(33, 'Cardiology'),
(33, 'Cardiothoracic Surgery'),
(33, 'Cosmetic Surgery'),
(33, 'Critical Care'),
(33, 'Dentistry and Maxillofacial Surgery'),
(33, 'Dermatology'),
(34, 'Anaesthesiology'),
(34, 'Cardiac Anesthesia'),
(34, 'Cardiology'),
(34, 'Cardiothoracic Surgery'),
(34, 'Critical Care'),
(34, 'Dentistry'),
(34, 'Dermatology'),
(34, 'Emergency Medicine'),
(35, 'Bariatric Surgery'),
(35, 'Cardiology'),
(35, 'Cardiothoracic Surgery'),
(35, 'Cosmetic Surgery'),
(35, 'Dentistry'),
(35, 'Dermatology'),
(35, 'Dietetics'),
(35, 'Endocrinology'),
(36, 'Cardiologist'),
(36, 'Ophthalmology'),
(36, 'Neurology'),
(36, 'Oncology'),
(36, 'Gynaecology'),
(37, 'Cardiology'),
(37, 'Cardiothoracic Surgery'),
(37, 'Critical Care'),
(37, 'Diabetology'),
(37, 'Nephrology'),
(37, 'Pediatric Cardiology'),
(38, 'Anesthesiology'),
(38, 'Audiology and Speech Therapy'),
(38, 'Cardiology'),
(38, 'Cardiothoracic Surgery'),
(38, 'Cardiovascular Surgery'),
(38, 'Chest Physician'),
(38, 'Colorectal Surgery'),
(38, 'Critical Care'),
(39, 'Anesthesiology'),
(39, 'Bio-Chemistry'),
(39, 'Dentistry'),
(39, 'General Medicine'),
(39, 'Homeopathy'),
(39, 'Medical Oncology'),
(39, 'Micro-Biology'),
(39, 'Pathology'),
(40, 'Andrology'),
(40, 'Audiology and Speech Therapy'),
(40, 'Cardiology'),
(40, 'Cardiovascular Surgery'),
(40, 'Colorectal Surgery'),
(40, 'Critical Care'),
(40, 'Dentistry'),
(40, 'Dermatology'),
(41, 'Anaesthesiology'),
(41, 'Cardiology'),
(41, 'Cardiothoracic Surgery'),
(41, 'Cosmetology'),
(41, 'Critical Care'),
(41, 'Dentistry'),
(41, 'Dermatology'),
(41, 'Diabetology'),
(42, 'Ayurveda'),
(42, 'Cardiology'),
(42, 'Cardiothoracic Surgery'),
(42, 'Cardiovascular Surgery'),
(42, 'Critical Care'),
(42, 'Dentistry'),
(42, 'Dermatology'),
(42, 'Diabetology'),
(43, 'Andrology'),
(43, 'Anaesthesiology'),
(43, 'Cardiology'),
(43, 'Critical Care'),
(43, 'Dentistry'),
(43, 'Dermatology'),
(43, 'Emergency Medicine'),
(43, 'Endocrinology'),
(44, 'Anaesthesiology'),
(44, 'Cardiology'),
(44, 'Cardiothoracic Surgery'),
(44, 'Cardiovascular Surgery'),
(44, 'Critical Care'),
(44, 'Dentistry and Maxillofacial Surgery'),
(44, 'Dermatology'),
(44, 'Diabetology'),
(45, 'Adolescent medicine'),
(45, 'Anaesthesiology'),
(45, 'Cardiology/ Cardiothoracic surgery'),
(45, 'Community/Behavioral medicine'),
(45, 'Critical care medicine'),
(45, 'Dermatology'),
(45, 'Emergency medicine'),
(45, 'ENT');

-- 3. Insert Simulated Indicative Room Categories (Enrichment)
INSERT INTO room_categories (id, hospital_id, name, daily_cost, available) VALUES
(32, 11, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(33, 11, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(34, 11, 'Single Private Deluxe AC', 6500.00, TRUE),
(35, 11, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(36, 12, 'Multi-Bed General Ward', 1200.00, TRUE),
(37, 12, 'Semi-Private Room AC', 3400.00, TRUE),
(38, 12, 'Single Standard AC Room', 5800.00, TRUE),
(39, 12, 'Super Deluxe Suite Room', 13500.00, TRUE),
(40, 13, 'Economy Sharing Ward', 1800.00, TRUE),
(41, 13, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(42, 13, 'Single Executive AC Room', 7200.00, TRUE),
(43, 13, 'Critical Care ICU Wing', 12500.00, TRUE),
(44, 14, 'General Ward (3-Bed)', 1400.00, TRUE),
(45, 14, 'Semi-Private AC Ward', 3600.00, TRUE),
(46, 14, 'Single Deluxe AC Room', 6200.00, TRUE),
(47, 14, 'Specialty ICU / CCU', 10500.00, TRUE),
(48, 15, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(49, 15, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(50, 15, 'Single Private Deluxe AC', 6500.00, TRUE),
(51, 15, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(52, 16, 'Multi-Bed General Ward', 1200.00, TRUE),
(53, 16, 'Semi-Private Room AC', 3400.00, TRUE),
(54, 16, 'Single Standard AC Room', 5800.00, TRUE),
(55, 16, 'Super Deluxe Suite Room', 13500.00, TRUE),
(56, 17, 'Economy Sharing Ward', 1800.00, TRUE),
(57, 17, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(58, 17, 'Single Executive AC Room', 7200.00, TRUE),
(59, 17, 'Critical Care ICU Wing', 12500.00, TRUE),
(60, 18, 'General Ward (3-Bed)', 1400.00, TRUE),
(61, 18, 'Semi-Private AC Ward', 3600.00, TRUE),
(62, 18, 'Single Deluxe AC Room', 6200.00, TRUE),
(63, 18, 'Specialty ICU / CCU', 10500.00, TRUE),
(64, 19, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(65, 19, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(66, 19, 'Single Private Deluxe AC', 6500.00, TRUE),
(67, 19, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(68, 20, 'Multi-Bed General Ward', 1200.00, TRUE),
(69, 20, 'Semi-Private Room AC', 3400.00, TRUE),
(70, 20, 'Single Standard AC Room', 5800.00, TRUE),
(71, 20, 'Super Deluxe Suite Room', 13500.00, TRUE),
(72, 21, 'Economy Sharing Ward', 1800.00, TRUE),
(73, 21, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(74, 21, 'Single Executive AC Room', 7200.00, TRUE),
(75, 21, 'Critical Care ICU Wing', 12500.00, TRUE),
(76, 22, 'General Ward (3-Bed)', 1400.00, TRUE),
(77, 22, 'Semi-Private AC Ward', 3600.00, TRUE),
(78, 22, 'Single Deluxe AC Room', 6200.00, TRUE),
(79, 22, 'Specialty ICU / CCU', 10500.00, TRUE),
(80, 23, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(81, 23, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(82, 23, 'Single Private Deluxe AC', 6500.00, TRUE),
(83, 23, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(84, 24, 'Multi-Bed General Ward', 1200.00, TRUE),
(85, 24, 'Semi-Private Room AC', 3400.00, TRUE),
(86, 24, 'Single Standard AC Room', 5800.00, TRUE),
(87, 24, 'Super Deluxe Suite Room', 13500.00, TRUE),
(88, 25, 'Economy Sharing Ward', 1800.00, TRUE),
(89, 25, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(90, 25, 'Single Executive AC Room', 7200.00, TRUE),
(91, 25, 'Critical Care ICU Wing', 12500.00, TRUE),
(92, 26, 'General Ward (3-Bed)', 1400.00, TRUE),
(93, 26, 'Semi-Private AC Ward', 3600.00, TRUE),
(94, 26, 'Single Deluxe AC Room', 6200.00, TRUE),
(95, 26, 'Specialty ICU / CCU', 10500.00, TRUE),
(96, 27, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(97, 27, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(98, 27, 'Single Private Deluxe AC', 6500.00, TRUE),
(99, 27, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(100, 28, 'Multi-Bed General Ward', 1200.00, TRUE),
(101, 28, 'Semi-Private Room AC', 3400.00, TRUE),
(102, 28, 'Single Standard AC Room', 5800.00, TRUE),
(103, 28, 'Super Deluxe Suite Room', 13500.00, TRUE),
(104, 29, 'Economy Sharing Ward', 1800.00, TRUE),
(105, 29, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(106, 29, 'Single Executive AC Room', 7200.00, TRUE),
(107, 29, 'Critical Care ICU Wing', 12500.00, TRUE),
(108, 30, 'General Ward (3-Bed)', 1400.00, TRUE),
(109, 30, 'Semi-Private AC Ward', 3600.00, TRUE),
(110, 30, 'Single Deluxe AC Room', 6200.00, TRUE),
(111, 30, 'Specialty ICU / CCU', 10500.00, TRUE),
(112, 31, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(113, 31, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(114, 31, 'Single Private Deluxe AC', 6500.00, TRUE),
(115, 31, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(116, 32, 'Multi-Bed General Ward', 1200.00, TRUE),
(117, 32, 'Semi-Private Room AC', 3400.00, TRUE),
(118, 32, 'Single Standard AC Room', 5800.00, TRUE),
(119, 32, 'Super Deluxe Suite Room', 13500.00, TRUE),
(120, 33, 'Economy Sharing Ward', 1800.00, TRUE),
(121, 33, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(122, 33, 'Single Executive AC Room', 7200.00, TRUE),
(123, 33, 'Critical Care ICU Wing', 12500.00, TRUE),
(124, 34, 'General Ward (3-Bed)', 1400.00, TRUE),
(125, 34, 'Semi-Private AC Ward', 3600.00, TRUE),
(126, 34, 'Single Deluxe AC Room', 6200.00, TRUE),
(127, 34, 'Specialty ICU / CCU', 10500.00, TRUE),
(128, 35, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(129, 35, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(130, 35, 'Single Private Deluxe AC', 6500.00, TRUE),
(131, 35, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(132, 36, 'Multi-Bed General Ward', 1200.00, TRUE),
(133, 36, 'Semi-Private Room AC', 3400.00, TRUE),
(134, 36, 'Single Standard AC Room', 5800.00, TRUE),
(135, 36, 'Super Deluxe Suite Room', 13500.00, TRUE),
(136, 37, 'Economy Sharing Ward', 1800.00, TRUE),
(137, 37, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(138, 37, 'Single Executive AC Room', 7200.00, TRUE),
(139, 37, 'Critical Care ICU Wing', 12500.00, TRUE),
(140, 38, 'General Ward (3-Bed)', 1400.00, TRUE),
(141, 38, 'Semi-Private AC Ward', 3600.00, TRUE),
(142, 38, 'Single Deluxe AC Room', 6200.00, TRUE),
(143, 38, 'Specialty ICU / CCU', 10500.00, TRUE),
(144, 39, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(145, 39, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(146, 39, 'Single Private Deluxe AC', 6500.00, TRUE),
(147, 39, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(148, 40, 'Multi-Bed General Ward', 1200.00, TRUE),
(149, 40, 'Semi-Private Room AC', 3400.00, TRUE),
(150, 40, 'Single Standard AC Room', 5800.00, TRUE),
(151, 40, 'Super Deluxe Suite Room', 13500.00, TRUE),
(152, 41, 'Economy Sharing Ward', 1800.00, TRUE),
(153, 41, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(154, 41, 'Single Executive AC Room', 7200.00, TRUE),
(155, 41, 'Critical Care ICU Wing', 12500.00, TRUE),
(156, 42, 'General Ward (3-Bed)', 1400.00, TRUE),
(157, 42, 'Semi-Private AC Ward', 3600.00, TRUE),
(158, 42, 'Single Deluxe AC Room', 6200.00, TRUE),
(159, 42, 'Specialty ICU / CCU', 10500.00, TRUE),
(160, 43, 'General Economy Ward (4-Bed)', 1500.00, TRUE),
(161, 43, 'Semi-Private (Twin Sharing AC)', 3800.00, TRUE),
(162, 43, 'Single Private Deluxe AC', 6500.00, TRUE),
(163, 43, 'Intensive Care Unit (ICU)', 11000.00, TRUE),
(164, 44, 'Multi-Bed General Ward', 1200.00, TRUE),
(165, 44, 'Semi-Private Room AC', 3400.00, TRUE),
(166, 44, 'Single Standard AC Room', 5800.00, TRUE),
(167, 44, 'Super Deluxe Suite Room', 13500.00, TRUE),
(168, 45, 'Economy Sharing Ward', 1800.00, TRUE),
(169, 45, 'Twin-Sharing Semi-Private AC', 4200.00, TRUE),
(170, 45, 'Single Executive AC Room', 7200.00, TRUE),
(171, 45, 'Critical Care ICU Wing', 12500.00, TRUE);

-- 4. Insert Simulated Insurer Network Mappings (Enrichment)
INSERT INTO network_hospitals (policy_id, hospital_id) VALUES
(1, 11),
(2, 11),
(3, 11),
(1, 13),
(2, 14),
(1, 15),
(3, 15),
(1, 17),
(2, 17),
(1, 19),
(3, 19),
(2, 20),
(1, 21),
(1, 23),
(2, 23),
(3, 23),
(1, 25),
(2, 26),
(1, 27),
(3, 27),
(1, 29),
(2, 29),
(1, 31),
(3, 31),
(2, 32),
(1, 33),
(1, 35),
(2, 35),
(3, 35),
(1, 37),
(2, 38),
(1, 39),
(3, 39),
(1, 41),
(2, 41),
(1, 43),
(3, 43),
(2, 44),
(1, 45)
ON CONFLICT DO NOTHING;

-- 5. Advance Database Sequences to prevent ID collisions
SELECT setval('hospitals_id_seq', (SELECT COALESCE(MAX(id), 1) FROM hospitals));
SELECT setval('hospital_specialties_id_seq', (SELECT COALESCE(MAX(id), 1) FROM hospital_specialties));
SELECT setval('room_categories_id_seq', (SELECT COALESCE(MAX(id), 1) FROM room_categories));
SELECT setval('network_hospitals_id_seq', (SELECT COALESCE(MAX(id), 1) FROM network_hospitals));
